# Generated by Django 5.0 on 2024-01-19 17:57

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_youtube_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='youtube_video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
